# Generated by Django 5.2.8 on 2025-11-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type_of_food",
                    models.CharField(
                        choices=[
                            ("UKRAINIAN", "Ukrainian"),
                            ("ASIAN", "Asian"),
                            ("ITALIAN", "Italian"),
                            ("FAST_FOOD", "Fast Food"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "restaurants",
                "ordering": ["-created_at"],
            },
        ),
    ]
