# Generated by Django 5.2.8 on 2025-11-21 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("menus", "0002_alter_menu_dishes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="accounts.employee",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="menus.menu",
                    ),
                ),
            ],
            options={
                "db_table": "votes",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "date"), name="unique_employee_date"
                    )
                ],
            },
        ),
    ]
